name: CD

on:
  release:
    types: [published]

env:
  FB_APP_ID: ${{ secrets.FB_APP_ID }}
  FB_APP_NAME: ${{ secrets.FB_APP_NAME }}
  GITHUB_OAUTH_CLIENT_ID: ${{ secrets.GH_OAUTH_CLIENT_ID }}
  GITHUB_OAUTH_CLIENT_SECRET: ${{ secrets.GH_OAUTH_CLIENT_SECRET }}
  FASTLANE_SUPPLY_JSON_KEY: ${{ secrets.FASTLANE_SUPPLY_JSON_KEY }}
  RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
  RELEASE_KEYSTORE_PROPERTIES: ${{ secrets.RELEASE_KEYSTORE_PROPERTIES }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.release.target_commitish == 'master'
    env:
      RELEASE_TYPE: ${{ contains(github.event.release.tag_name, 'beta') && 'beta' || 'prod' }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter clean
      - run: flutter pub get

      - run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - run: flutter format --set-exit-if-changed .

      - run: flutter analyze .

      - run: echo "${FASTLANE_SUPPLY_JSON_KEY}" | base64 --decode > android/supply_json_key.json

      - run: echo "${RELEASE_KEYSTORE_PROPERTIES}" | base64 --decode > android/key.release.properties

      - run: echo "${RELEASE_KEYSTORE}" | base64 --decode > android/app/cv_release.jks

      - run: flutter build appbundle --dart-define=FB_APP_ID=${FB_APP_ID} --dart-define=FB_APP_NAME=${FB_APP_NAME} --dart-define=GITHUB_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID} --dart-define=GITHUB_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}

      - uses: maierj/fastlane-action@v3.1.0
        with:
          lane: ${{ env.RELEASE_TYPE }}
          subdirectory: android
